---
driver:
  #name: vagrant
  name: ec2
  aws_ssh_key_id: selvamuswest2
  region: us-west-2
  availability_zone: a
  subnet_id: subnet-07a02a4f
  instance_type: t2.micro
  image_id: ami-79873901
  security_group_ids: ["sg-b4d499c9"]
  retryable_tries: 12
  
provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  product_name: chef
  product_version: 13.7.16
  #12.21.31
  #always_update_cookbooks: true
  deprecations_as_errors: true
 
transport:
  ssh_key: ../../selvamuswest2.pem

platforms:
  - name: ubuntu-16.04
  #- name: centos-7.2 
  
suites:
  - name: default
    run_list:
      - recipe[custom_apache::default]
    attributes:
